language: java
jdk: openjdk8
dist: xenial

install:
  # Installing Android SDK
  - curl https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip --output $HOME/android-sdk.zip
  - unzip -qq $HOME/android-sdk.zip -d $HOME/android-sdk
  - export ANDROID_SDK_HOME=$HOME/android-sdk
  - export ANDROID_NDK_HOME=$ANDROID_SDK_HOME/ndk/20.1.5948944
  # Installing necessary components of Android SDK
  - function installAndroidComponent() { yes | ${ANDROID_SDK_HOME}/tools/bin/sdkmanager $1 > /dev/null; }
  - installAndroidComponent "ndk;20.1.5948944"
  - installAndroidComponent "cmake;3.10.2.4988404"
  # Installing meson, ninja and nasm that are necessary for libdav1d building
  - sudo apt-get install python3-pip python3-setuptools python3-wheel ninja-build
  - sudo pip3 install meson==0.52.1
  - chmod +x build.sh
script:
  - bash -e build.sh
before_deploy:
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')}
deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: hello_world_$TARGET
  skip_cleanup: true
  draft: true
  on:
    repo:  jurkov/hello-world-with-travis-for-android 
    branches:
      only:
        - master
